### ISSUE TITLE
File organization

### ISSUE THREAD

**Issue by taalas** [BSData/warhammer-age-of-sigmar#1]
With the basic rules and the Warscrolls for legacy armies now available it might make sense to discuss how to organize the new files. Since units can now be mixed it might make sense to no~~w~~*t* have a single file per faction, but instead move to one file per Grand Alliance. From what I read so far it is still very unclear how army composition will work in detail, though.

Would starting on the files make sense at this point or is it better to wait until it is clearer how the system is supposed to work and the first per-unit Warscrolls come in with the new models?

**Comment by amis92** [comment]
I *think* that the work can start, and file per Alliance is quite an idea. If the files would then need to be separated into factions, it's easier to copy over than the other way (merging). Also there is such an amount of Warscrolls available now that there is no need to wait for actual *new* rules. Not much will change, I suppose.

**Comment by taalas** [comment]
I added first drafts as a proposal for the Age of Sigmar game system and the Order catalogue. Please let me know if I am completely on the wrong track with this.

**Comment by Captain-Joystick** [comment]
Factions seem to have common keywords anyway, is it possible to have then be the subcategories after selecting grand alliance? 

Inversely, what real rules prevent you from taking a unit of chaos, a unit of bretonians, and throwing lore at it? I have only read the '4-pages' and don't recall anything saying I can't.

Also, from a useability standpoint, breaking it down by faction means you're loading less unit data when you create your list on the mobile app, right? And 90% of the time the player is probably going mono-faction anyway. Furthermore, if a unit's data was to somehow have a horrible error that caused the app to crash on army generation, impact would be reduced to that faction instead of the whole alliance. It's also possible that future updates may impact many factions simultaneously, in which case wouldn't it be better for different users to be able to edit factions independently?

I'm not really contributing anything here but I feel like the grand alliance is too big and unwieldly to be a significant factor in every single list, and should instead be easily represented like the way the 40k data handles allies.

**Comment by taalas** [comment]
Yes, factions have common keywords (e.g. the Order alliance will share the "Order" keyword" among factions). For the current game system proposal I did exactly what you describe, having the factions be sub-categories of their respective alliance.

I know what you mean regarding the rules: As they are now it seems army composition is not limited to alliances, let's be honest though...the current rules leave a couple of things to imagination ;)
I think it was clearly stated by GW that armies should consist of alliance members but I can check where this comes from...

Having started the files I agree that alliances might be too big of a collection on second thought. Alliances are very different in size, the Order alliance alone is almost too big to really handle well in one file though if on mobile. Desktop devices won't have any problems and since the factions are sub-categories there is order to the way it is displayed. Might be best to split them up though...for now this is almost only a file rename...

**Comment by cartag** [comment]
Loading the entire alliance in one catalog would be huge. I'd suggest splitting them up. I'm working on Daemons now, I'll upload my progress.

**Comment by taalas** [comment]
As I wrote earlier I agree. As long as there is a clear definition of what files there will be, splitting them up is a good idea.

**Comment by chevalric** [comment]
I think using separate files per faction makes it easier to keep an overview, but of course, that will require some duplication (mostly for the keywords, so not too bad). For BS it doesn't matter, it doesn't limit you when you want to join Chaos and Order forces together.

**Comment by flakpanda** [comment]
Closed due to age
