### ISSUE TITLE
Set increments of 10?

### ISSUE THREAD

**Issue by kentachi** [BSData/warhammer-age-of-sigmar#135]
How can I create custom unit sizes? For example, I can only have saurus warriors in increments of 10? How do I have set it to 12?

**Comment by alphalas** [comment]
It's because you can only buy them in increments of 10 –  even if you only use 12 you still have to pay for 20, RAW.

**Comment by kentachi** [comment]
The start collecting kit comes with 12

**Comment by alphalas** [comment]
Doesn't matter – you buy them in the increments that are listed in the handbook.

**Comment by alphalas** [comment]
You can have understrength units, however they have the same cost as a full strength unit built to the next increment. It's something that we could implement with the re-factor of the system – right now you can't.

**Comment by kentachi** [comment]
I see. So a unit of 12 will cost the same as 20?

**Comment by alphalas** [comment]
Yes exactly.

**Comment by OftKilted** [comment]
This is directly referenced in the "Pitched Battles - Picking your Army" on p. 106 in the Generals Handbook and Under Strength units are directly referenced on p. 107

“UNDER-STRENGTH UNITS
Sometimes you may find that you do not have enough models to field a unit at full strength; if this is the case, you must still pay the full cost of the unit.
For example, if you decided to field a unit of 3 Liberators, rather than a full-strength unit with 5 models, the unit would still cost 100 points.” GHB P. 107

You could field one unit of 10 and another unit of 2, but 
also be aware that there is a limitation of only fielding one unit of Under strength and under sized as referenced in the v1.1 of the FAQ for the GHB (2016)

"Q: In Pitched Battles, does the Under-strength Units rule override the restriction in the rules for warscrolls that says you can only  field one unit that is of less than the minimum size?
A: No. Also, note that a unit can be ‘under-strength’ and still above minimum size. For example, a unit of 7 Liberators would be above the minimum size but still under-strength." GHB FAQ (2016) v1.1 p. 2
