### ISSUE TITLE
Legion of Chaos Ascendant still broken

### ISSUE THREAD

**Issue by BriB23** [BSData/warhammer-age-of-sigmar#1361]
Someone needs to go over this with a fine-toothed comb or just redo it altogether. There are characters who, when chosen as general, aren't able to take command traits, artifacts, spells, etc. Forge World daemon units still aren't in the list. Except for the Verminlord Corrupter, why are all of the Skaven daemons and endless spells in some wierd category called "Uncategorized"?

**Comment by cartag** [comment]
Parts will likely have to be redone entirely due to the curve ball GW threw with the new "faction." Thank you for your GENEROUS outpouring of support. 

Named characters shouldn't be able to take traits/artefacts/spells. 

Which Forge World daemon units are you referring to? Everything in the download rules from FW are in there. 

The Skaven ones are uncategorized because they are an old file structure that the newer files have set up differently. Long story short, I didn't want to spend hours of my life changing something that wouldn't <censored> matter.

**Comment by cartag** [comment]
More specific information is helpful rather than broad general statements, like which units aren't in the file, which units are missing traits/artefacts/spells, etc.

**Comment by cartag** [comment]
The Skaven one being uncategorized shouldn't be happening any more, that was fixed... I'll double check it.

**Comment by BriB23** [comment]
As an example, try creating this list: https://www.belloflostsouls.net/2020/05/aos-list-of-the-week-chaos-ascendant.html

Since Forgeworld is currently shut down, I can't list the daemon units from there other than the one in the list above.
[http://www.belloflostsouls.net/wp-content/uploads/2020/02/legionofchaosascendant-aos.jpg]<https://www.belloflostsouls.net/2020/05/aos-list-of-the-week-chaos-ascendant.html>
AoS List Of The Week - Chaos Ascendant - Bell of Lost Souls<https://www.belloflostsouls.net/2020/05/aos-list-of-the-week-chaos-ascendant.html>
AoS List Of The Week – Chaos Ascendant. J.R. Zambrano May 3. 9. Tournaments are back… sort of. And that means a new top list! Find out more as we bring you the top championship list in Age of Sigmar – brought to you by BCP. Welcome, Age of Sigmar players. Today we have your weekly report of all things competitive AoS.
www.belloflostsouls.net


________________________________
