### ISSUE TITLE
Legions of Nagash and Nighthaunt

### ISSUE THREAD

**Issue by jdward91** [BSData/warhammer-age-of-sigmar#1817]
When I use the Battlescribe desktop app, I can use the catalogue Death - Legions of Nagash, but on the mobile it's Death: Legions of Nagash and Nighthaunt, which is the data library. This error may well be why when I write lists on one they don't work on the other.

**Comment by jdward91** [comment]
Good point, I'm on Android. Data fully purged twice, still an error.

**Comment by cartag** [comment]
The other thing that stands out to me is that your Legions of Nagash and Nighthaunt data file is too high in its data number. As far as I can tell, it should be, at most, v38. I don't know how you managed to get v42. Can you share screenshots of your Manage Data screen, so we can see what repositories you have selected?

**Comment by jdward91** [comment]
Of course. This is all of them. 
![Screenshot_20210507-173759](https://user-images.githubusercontent.com/40031981/117481622-24d8ba00-af5b-11eb-87c7-d7ae76437bdd.png)

**Comment by cartag** [comment]
If you would have deleted your data, it would have deleted that v42 file and replaced it with one that is v38. I don't even know how you managed to get a v42 file for Death - Legions of Nagash and Nighthaunt Data.cat. I can't even see when there's been a v42 on the repo at all. 

The reason it's not being replaced when you update and don't delete the data is because v42 is higher than v38, so BS thinks it's keeping a more updated file and not replacing it with something old. I'm at a loss as to how you managed to get a file that doesn't exist on the repo.

**Comment by jdward91** [comment]
With respect, I did delete it twice, as well as remove it from Dropbox. I've just done it again, and, as you can tell by the time, got the same issue.
![Screenshot_20210507-180646](https://user-images.githubusercontent.com/40031981/117484795-7d11bb00-af5f-11eb-8b59-361d0591f6c6.png)
![Screenshot_20210507-180836](https://user-images.githubusercontent.com/40031981/117484837-8733b980-af5f-11eb-9732-61de4cf3b4d3.png)
![Screenshot_20210507-180656](https://user-images.githubusercontent.com/40031981/117484839-87cc5000-af5f-11eb-8ad8-ebeecbfb36a1.png)
![Screenshot_20210507-180740](https://user-images.githubusercontent.com/40031981/117484842-8864e680-af5f-11eb-978c-ffba72ff12eb.png)

**Comment by cartag** [comment]
By deleting I don't mean unchecking it from the menu, updating, checking it, then updating again. When you try to update, the following screen should come up. Check this and then update. If you have it synced with Dropbox, you can try replacing the files on PC with a download from github and that should replace the files. I am 95% certain right now the issue is with your device because of the v42 file. If it were an issue with Battlescribe not showing library files correctly, you would be seeing a Chaos Data.cat file when trying to create a new roster. That's not happening, so it narrows it down to that one file. Once we can get it removed and replaced, it should be working correctly. 

![2021-05-07 11 32 29](https://user-images.githubusercontent.com/4388344/117487144-eece1280-af27-11eb-8f9e-ce77d8ddf481.png)

**Comment by jdward91** [comment]
I didn't do that, but OK. I went full purge on Dropbox, my phone, and all other data sources, and I think it's now working. Thanks for the help!
![Screenshot_20210507-184345](https://user-images.githubusercontent.com/40031981/117488806-bb5da900-af64-11eb-84d0-1642758005b2.png)
![Screenshot_20210507-184159](https://user-images.githubusercontent.com/40031981/117488809-bc8ed600-af64-11eb-8442-ffbee35f54f0.png)
![Screenshot_20210507-184215](https://user-images.githubusercontent.com/40031981/117488811-bc8ed600-af64-11eb-96c0-4f7b436ea71f.png)
![Screenshot_20210507-183939](https://user-images.githubusercontent.com/40031981/117488815-bd276c80-af64-11eb-81b7-446620d4fc57.png)
![Screenshot_20210507-184516](https://user-images.githubusercontent.com/40031981/117488818-bd276c80-af64-11eb-85c3-9234929381b9.png)
![Screenshot_20210507-184358](https://user-images.githubusercontent.com/40031981/117488824-bdc00300-af64-11eb-9f8d-438cbeb9ffe0.png)
![Screenshot_20210507-184403](https://user-images.githubusercontent.com/40031981/117488825-be589980-af64-11eb-8738-ba1a3e0ab9e9.png)

**Comment by cartag** [comment]
I'm glad it's working for you now! Just to confirm, both the Legions of Nagash file and the Nighthaunt file should be showing as v8, is that correct? I just want to make sure it's showing as it should now that we've gotten this far.

**Comment by jdward91** [comment]
Yes! That screenshot didn't take apparently.
![Screenshot_20210507-194738](https://user-images.githubusercontent.com/40031981/117495204-39be4900-af6d-11eb-96ba-a637a3d742f9.png)
