### ISSUE TITLE
Bug report: Kharadron Overlords - Double Grundstok Thunderers as battleline

### ISSUE THREAD

**Issue by plavski** [BSData/warhammer-age-of-sigmar#1937]
AoS 3.0.2

1. Set Allegiance to Barak Nar
2. Set Arkanaut Admiral as General

Grundstok Thunderers appear twice in Battleline options
![image](https://user-images.githubusercontent.com/15157275/124512899-72de3280-ddd1-11eb-808b-e7b005e771ab.png)

**Comment by blackeclipsevii** [comment]
this bug also occurs with grave guard in soulblight gravelords

- add a wight king
- set the wight king as general (grave guard will be set to battleline)
- add another leader and set to general (just add mannfred)
- grave guard will appear as battleline twice, and remain 2x until the wight king is no longer a general

If the condition to set the grave guard as battleline is removed (is wight king a general?) the above issue never occurs.
---
When reproducing the Grundstok Thunderers issue above I attempted to reproduce the issue a number of different ways (different leaders, allegiances, etc.) and also ended up with multiple Arkanaut Frigates that never went away.

**Comment by cartag** [comment]
This is by nature a BS bug that we will need to change catalogue behaviors to work around. It is not a bug with the data.

**Comment by cartag** [comment]
This is a bug with Battlescribe, and it takes some explaining as to why this is the preferred method of doing things. 

Your Thunderers are only brought as Battleline if certain criteria are met. How it is set up now, if that criteria is met halfway through building a list, the Thunderers will automatically switch between Other units and Battleline units. There is another way we can set it up, to where the duplication will not show up, but the units will not switch from Other to Battleline, and it will require you to remove the units and readd them to change their battlefield role. 

It's annoying that it shows up twice, but the units showing up in the selection panel multiple times doesn't actually affect your ability to make a list, it just looks wonky. I can offer a more technical explanation if requested, going into finer detail, but the short answer is "We know it happens, and it's going to continue to happen, because the alternative is more of a pain in the ass and the BS app dev is MIA and it won't get fixed anytime soon."

**Comment by plavski** [comment]
Thanks for the update, closing.
