### ISSUE TITLE
Request: Working Allies/Mercenaries

### ISSUE THREAD

**Issue by JoshRow** [BSData/warhammer-age-of-sigmar#2089]
Right now I don't believe there's a way to integrate Allies/Mercenaries into a list, you have to add them as their own thing which means the roster thinks they need Battleleline and all that. Would be good to just have a menu for both offerings although I understand that's probably a lot of additional work.

**Comment by cartag** [comment]
If you add a sub-force to your primary force you can add Allies/Coalition units (#2030). Correct me if I'm wrong, but I think the only mercenary units available right now are the three mega gargants and Gotrek. Since those are the only mercs, they have just been added directly to lists that can take them as available options.

**Comment by JoshRow** [comment]
You are correct.

**Comment by cartag** [comment]
The subforce method does not require battleline entries for the sub forces, nor do they count if you add them. You can also add them to core battalions. Does that resolve your request?
