### ISSUE TITLE
Lumineth Great Nation Battleline

### ISSUE THREAD

**Issue by DaveHSheff** [BSData/warhammer-age-of-sigmar#2122]
Alarith Stoneguard work correctly – they become Battleline in both the Available Units (left) and Selected Units (centre) columns, they count towards the required number of Battleline units in the army, and they can be reinforced twice when Ymetrica Great Nation is selected. The only minor issue is that they retain the Other category when they are Battleline.

Hurakan Windchargers work correctly – as above when Helon Great Nation is selected.

**Comment by DaveHSheff** [comment]
I realise this is a trivial issue, but I have a simple fix for it and I'm using this to test my process for submitting changes

**Comment by DaveHSheff** [comment]
Please can you give me some feedback regarding whether this is the correct way to submit changes, and the level of detail about the change I gave in the description.

Thanks,
Dave

**Comment by cartag** [comment]
Honestly most of the time we don't bother with removing the Other category, as Other isn't really a keyword and is only there to be used as a catch-all for anything that's not Battleline, Behemoth, Artillery, or Leader. I don't believe we regularly remove it from any catalogues that have conditional battleline units. That being said, I can merge it since it's a simple fix that you've already done the work for. 

 If you'd like to become a data author, please talk with us on Discord (https://discord.gg/UrrPB3T); AoS is a pretty busy repo and there's a lot of updates that get pushed frequently.
