### ISSUE TITLE
Uniques and ally enhancements

### ISSUE THREAD

**Issue by exaegrum** [BSData/warhammer-age-of-sigmar#2253]
As of 3.0.21, Unique units are still able to take universal spell lores(and presumably prayers, though I couldn't think of a unique PRIEST to test). In addition, allied units can pick universal artefacts/spell lores/prayers and in edge cases like Olynder, spell lores they have the keyword for.

**Comment by cartag** [comment]
This is a situation where a fix was done, and works, but there was a completely separate bug that makes itself known at the same time. It seems the unique Death characters aren't labeled as Unique, which is the second thing. Thanks for reporting the issue as still unresolved, it'll be fixed in the next release.

**Comment by cartag** [comment]
Went through all catalogs and flagged Unique units as such. This should prevent Universal Spell Lores or Prayer lists to show for Unique Wizards or Priests.

**Comment by exaegrum** [comment]
Is the allies taking artefacts/spell lores also a separate issue, or was that related?
